name: Issues workflow
on:
  issues:
    types: [opened, edited, reopened, closed]

jobs:
  info:
    runs-on: ubuntu-latest
    env:
      ACTIONS_RUNNER_DEBUG: true
    steps:
      - name: Output GitHub event
        run: |
            echo "GitHub event:" 
            echo "${{ toJson(github.event) }}"
      - name: Output Issue
        run: echo "${{ toJson(github.event.issue) }}"
      - name: Output Issue Title
        run: echo "${{ github.event.issue.title }}"
      - name: Output Issue Body
        run: echo "${{ github.event.issue.body }}"
      - name: Output Issue State
        run: echo "${{ github.event.issue.state }}"
      - name: Output Issue URL
        run: echo "${{ github.event.issue.html_url }}"