name: Issues workflow
on:
  issues:
    types: [opened, edited, reopened, closed]

jobs:
  info:
    runs-on: windows-latest
    env:
      ACTIONS_RUNNER_DEBUG: true
    steps:
    
      - name: Output Issue
        shell: bash
        run: printf "${{ toJson(github.event.issue) }}"
      - name: Output Issue Title
        shell: bash
        run: printf "${{ github.event.issue.title }}"
      - name: Output Issue Body
        shell: bash
        run: printf "${{ github.event.issue.body }}"
      - name: Output Issue State
        shell: bash
        run: printf "${{ github.event.issue.state }}"
      - name: Output Issue URL
        shell: bash
        run: printf "${{ github.event.issue.html_url }}"