name: Issues workflow
on:
  issues:
    types: [opened, edited, reopened, closed]

jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Output GitHub event
        run: echo "${{ toJson(github.event) }}"
      - name: Output Issue
        run: echo "${{ toJson(github.event.issue) }}"
      - name: Output Issue Title
        run: echo "${{ github.event.issue.title }}"
      - name: Output Issue Body
        run: echo "${{ github.event.issue.body }}"
      - name: Output Issue State
        run: echo "${{ github.event.issue.state }}"
      - name: Output Issue URL
        run: echo "${{ github.event.issue.html_url }}"
      - name: Output Issue Author 
        run: echo "${{ github.event.issue.user.login }}"
      - name: Output Issue Labels 
        run: echo "${{ toJson(github.event.issue.labels) }}"
      - name: Output Issue Comments URL       
        run: echo "${{ github.event.issue.comments_url }}"            