name: workflow reusable test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency: ci-${{ github.workflow }}-

jobs:
  build:
    uses: juliancho923/gh-first-action/.github/workflows/reusable-workflow.yml@main
    with:
        config-path: "config example"
